[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "16bit_helper"
version = "0.0.1"
requires-python = ">=3.7"

[tool.setuptools.packages]
find = {}
